#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_Reflected_Raw)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float kp,kd,ki;
int v=100;
int u,err,errold;
int alpha=0;

task alphaturn()
{
	while(true)
	{
		motor[motorB]=alpha-nMotorEncoder[motorB];
	}
}
task main()

{
	startTask (alphaturn);
	kp=0.6;
	kd=0.6;
	ki=0;
	while(true)
	{
		displayBigTextLine(4,"%d",SensorValue[s1]);
		displayBigTextLine(6,"%d",SensorValue[s3]);
		err=SensorValue[s1]-SensorValue[s3];
		errold=err;
		u=err*kp+errold*kd;

		motor[motorC]=-100;
		alpha=-u;

	}

}
